### ISSUE TITLE
Does not start on OSX

### ISSUE THREAD

**Issue by PhilAndrew** [visionmedia/screenshot-app#14]
orsamac:screenshot-app orsa$ node app

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/orsa/home/projects/zero/screenshot-app/node_modules/canvas/build/Release/canvas.node, 1): Symbol not found: _FT_Done_Face
  Referenced from: /Users/orsa/home/projects/zero/screenshot-app/node_modules/canvas/build/Release/canvas.node
  Expected in: dynamic lookup

```
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/Users/orsa/home/projects/zero/screenshot-app/node_modules/canvas/lib/bindings.js:2:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

orsamac:screenshot-app orsa$

**Comment by aksbhatia** [comment]
npm install with Error!

---

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-d"

npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0.
gyp ERR! configure error 
gyp ERR! stack Error:`gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)

---

Any idea?

Because of this, the server startup is failing....
LM-BLR-00668417:screenshot-app aksbhatia$ node app

app.configure(function(){
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous>

**Comment by cmpolis** [comment]
I had similar install issues that were fixed by `brew install cairo` and rerunning install.

**Comment by tj** [comment]
Cairo is a pretty big pain to install. I don't recall why it's even in this repo haha, just Phantom should be fine. This repo is a little outdated but figured it might be annoying if I removed it
